return function(cp)
	return {
		-- Text
		["@text"]                      = { fg = cp.purple },
		["@text.strong"]               = { fg = cp.purple, bold = true },
		["@text.emphasis"]             = { fg = cp.purple, italic = true },
		["@text.underline"]            = { fg = cp.purple, underline = true },
		["@text.strike"]               = { fg = cp.purple, strikethrough = true },
		["@text.title"]                = { fg = cp.green, bg = cp.red, bold = true },
		["@text.literal"]              = { fg = cp.green },
		["@text.uri"]                  = { fg = cp.cyan, underline = true },
		["@text.math"]                 = { fg = cp.yellow },
		["@text.reference"]            = { fg = cp.cyan },
		["@text.environment"]          = { fg = cp.yellow },
		["@text.environment.name"]     = { fg = cp.yellow, bold = true },
		["@text.note"]                 = { fg = cp.white_dimm },
		["@text.warning"]              = { fg = cp.warning },
		["@text.danger"]               = { fg = cp.error },
		["@text.diff.add"]             = { fg = cp.ok },
		["@text.diff.delete"]          = { fg = cp.error },
		["@comment"]                   = { fg = cp.white_dark, italic = true },
		["@comment.documentation"]     = { fg = cp.white_dark, bold = true, italic = true },
		["@special.comment"]           = { fg = cp.white_dark, bold = true },
		["@comment.error"]             = { fg = cp.error },
		["@preproc"]                   = { fg = cp.orange },
		-- Keyword
		["@keyword"]                   = { fg = cp.cyan },
		["@keyword.function"]          = { fg = cp.cyan, bold = true },
		["@keyword.operator"]          = { fg = cp.cyan },
		["@keyword.return"]            = { fg = cp.cyan },
		["@conditional"]               = { fg = cp.cyan },
		["@repeat"]                    = { fg = cp.cyan },
		-- Html
		["@tag"]                       = { fg = cp.yellow },
		["@tag.delimiter"]             = { fg = cp.violet },
		["@tag.name"]                  = { fg = cp.yellow },
		["@tag.builtin"]               = { fg = cp.yellow },
		-- XML
		["@tag.attribute.xml"]         = { fg = cp.violet },
		["@tag.xml"]                   = { fg = cp.yellow },
		["@punctuation.delimiter.xml"] = { fg = cp.green },
		-- Statement
		["@debug"]                     = { fg = cp.orange },
		["@statment"]                  = { fg = cp.cyan },
		["@include"]                   = { fg = cp.cyan },
		["@define"]                    = { fg = cp.cyan },
		["@macro"]                     = { fg = cp.magenta },
		-- Identifier
		["@identifier"]                = { fg = cp.purple },
		["@property"]                  = { fg = cp.purple },
		["@variable"]                  = { fg = cp.purple },
		["@variable.builtin"]          = { fg = cp.purple, bold = true },
		["@variable.property"]         = { fg = cp.purple },
		["@variable.parameter"]        = { fg = cp.purple },
		["@variable.function"]         = { fg = cp.purple, bg = cp.red, bold = true },
		["@variable.member.query"]     = { fg = cp.red, bold = true },
		-- Function
		["@function"]                  = { fg = cp.purple, bold = true },
		["@function.call"]             = { fg = cp.purple, bold = true },
		["@function.builtin"]          = { fg = cp.purple, bold = true },
		["@function.macro"]            = { fg = cp.purple, bold = true },
		["@lsp.type.function"]         = { fg = cp.purple, bold = true },
		["@lsp.type.method"]           = { fg = cp.purple, bold = true },
		["@parameter"]                 = { fg = cp.cyan },
		["@method.call"]               = { fg = cp.purple, bold = true },
		["@method"]                    = { fg = cp.purple, bold = true },
		["@constructor"]               = { fg = cp.magenta, bold = true },
		["@constructor.lua"]           = { fg = cp.violet },
		["@label"]                     = { fg = cp.cyan, bold = true },
		-- Type
		["@type"]                      = { fg = cp.yellow },
		["@type.builtin"]              = { fg = cp.yellow, bold = true },
		["@type.qualifier"]            = { fg = cp.yellow },
		["@type.definition"]           = { fg = cp.yellow, bold = true },
		["@storageclass"]              = { fg = cp.yellow },
		["@namespace"]                 = { fg = cp.yellow },
		["@constant"]                  = { fg = cp.magenta, bold = true },
		["@constant.builtin"]          = { fg = cp.magenta, bold = true },
		["@constant.macro"]            = { fg = cp.magenta, bold = true },
		-- Lsp Type
		["@lsp.type.structure"]        = { fg = cp.yellow, bold = true },

		-- Literal
		["@null"]                      = { fg = cp.yellow },
		["@string"]                    = { fg = cp.green },
		["@string.regex"]              = { fg = cp.magenta },
		["@string.escape"]             = { fg = cp.magenta },
		["@string.special"]            = { fg = cp.magenta },
		["@string.special.url"]        = { fg = cp.cyan, underline = true },
		["@character"]                 = { fg = cp.red },
		["@character.special"]         = { fg = cp.red, bold = true },
		["@number"]                    = { fg = cp.red },
		["@boolean"]                   = { fg = cp.red },
		["@float"]                     = { fg = cp.red },
		-- Punctuation
		["@attribute"]                 = { fg = cp.purple, bold = true },
		["@attribute.value"]           = { fg = cp.red },
		["@tag.attribute.javascript"]  = { fg = cp.purple }, -- TODO: check if that is html or js
		["@punctuation.bracket"]       = { fg = cp.violet },
		["@punctuation.delimiter"]     = { fg = cp.violet },
		["@punctuation.special"]       = { fg = cp.violet },
		-- Operator
		["@operator"]                  = { fg = cp.magenta, bold = true },
	}
end
