return function(cp)
	return {
		rustSelf                                         = { fg = cp.purple, bold = true },
		rustModPath                                      = { fg = cp.yellow },
		rustAttribute                                    = { fg = cp.violet },
		rustAttributeParenthesizedParens                 = { fg = cp.purple },
		rustIdentifier                                   = { fg = cp.yellow },
		["@lsp.typemod.generic.attribute.rust"]          = { fg = cp.pink },
		["@lsp.typemod.operator.macro.rust"]             = { fg = cp.violet },
		["@lsp.typemod.derive.attribute.rust"]           = { fg = cp.pink },
		["@lsp.typemod.attributeBracket.attribute.rust"] = { fg = cp.violet },
		["@lsp.typemod.selfKeyword.declaration.rust"]    = { fg = cp.purple, bold = true },
		["@lsp.typemod.builtinAttribute.attribute.rust"] = { fg = cp.purple },
		["@lsp.type.attributeBracket.rust"]              = { fg = cp.violet },
		["@lsp.type.builtinAttribute.rust"]              = { fg = cp.yellow, bold = true },
		["@lsp.typemod.lifetime.declaration.rust"]       = { fg = cp.pink },
		["@lsp.type.lifetime.rust"]                      = { fg = cp.pink },
		["@lsp.typemod.namespace.attribute.rust"]        = { fg = cp.purple },
		["@lsp.typemod.namespace.procMacro.rust"]        = { fg = cp.cyan },
		["@lsp.type.const.rust"]                         = { fg = cp.magenta, bold = true },
		["@lsp.type.namespace.rust"]                     = { fg = cp.yellow },
		["@module.rust"]                                 = { fg = cp.yellow },
		['@lsp.typemod.namespace.macrop.rust']           = { fg = cp.yellow },
		["@lsp.mod.intraDocLink.rust"]                   = { fg = "#C38C23" },

		rustFoldBraces                                   = { fg = cp.violet },
		rustLifetime                                     = { fg = cp.pink },
		rustSigil                                        = { fg = cp.magenta },
	}
end
